/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-dropdown-menu-shared-styles.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

/// <reference path="../paper-styles/default-theme.d.ts" />

